// Successful Post
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "021-23456789"
}

###
// Failed Post
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "NN",
    "number": "021-23456789"
}